# Generated by Django 5.2.4 on 2025-08-08 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleWebhookChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_account_id', models.PositiveIntegerField(blank=True, help_text='allauth SocialAccount.id', null=True)),
                ('channel_id', models.CharField(max_length=255)),
                ('resource_id', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('social_account_id', 'channel_id')},
            },
        ),
        migrations.CreateModel(
            name='OutlookWebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_account_id', models.PositiveIntegerField(blank=True, help_text='allauth SocialAccount.id', null=True)),
                ('subscription_id', models.CharField(max_length=255)),
                ('expiration_datetime', models.DateTimeField()),
            ],
            options={
                'unique_together': {('social_account_id', 'subscription_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncedCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft')], max_length=50)),
                ('calendar_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_sync_enabled', models.BooleanField(default=True)),
                ('social_account_id', models.PositiveIntegerField(blank=True, help_text='allauth SocialAccount.id', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'provider', 'calendar_id')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_enabled', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('teams', 'Teams'), ('local', 'Local')], default='local', max_length=50)),
                ('event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('synced_calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler_app.syncedcalendar')),
            ],
            options={
                'unique_together': {('user', 'source', 'event_id')},
            },
        ),
    ]
