# Generated by Django 5.2.4 on 2025-08-27 07:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, max_length=500, null=True)),
                ('source', models.CharField(choices=[('google', 'Google'), ('microsoft', 'Microsoft'), ('local', 'Local'), ('booked_meeting', 'Booked Meeting')], db_index=True, default='local', max_length=50)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('calendar_provider_id', models.CharField(blank=True, help_text="The ID of the calendar this event belongs to, from the provider's API.", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleWebhookChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255, unique=True)),
                ('resource_id', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='OutlookWebhookSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True)),
                ('expiration_datetime', models.DateTimeField()),
                ('social_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SyncedCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(help_text="The unique ID of the calendar from the provider (e.g., Google's calendarId)", max_length=255)),
                ('name', models.CharField(help_text='The display name of the calendar', max_length=255)),
                ('provider', models.CharField(max_length=30)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full_details', 'Full Details'), ('private', 'Private Appointment (Busy/Free)')], default='full_details', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('destination_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_relations', to='scheduler_app.syncedcalendar')),
                ('source_calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='scheduler_app.syncedcalendar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_event_id', models.CharField(db_index=True, max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('source_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.event')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler_app.syncrelationship')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharing_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('primary_booking_calendar', models.ForeignKey(blank=True, help_text='The social account to use for creating booked events and sending invitations.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.socialaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('social_account', 'event_id'), name='unique_event_per_social_account'),
        ),
        migrations.AlterUniqueTogether(
            name='syncedcalendar',
            unique_together={('social_account', 'calendar_id')},
        ),
        migrations.AlterUniqueTogether(
            name='eventmapping',
            unique_together={('relationship', 'source_event')},
        ),
    ]
