# Generated by Django 5.2.4 on 2025-08-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncedcalendar',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
