# Generated by Django 5.2.4 on 2025-08-04 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0006_googlewebhookchannel_expiration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlewebhookchannel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_webhook_channel', to=settings.AUTH_USER_MODEL),
        ),
    ]
