# Generated by Django 5.2.4 on 2025-08-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0009_event_is_recurring_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('google', 'Google'), ('outlook', 'Outlook'), ('teams', 'Teams'), ('local', 'Local')], default='local', max_length=50),
        ),
    ]
